version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: bbdd-tracer
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracer

  tracer_api:
    image: tracer_api:latest
    build:
      context: ./tracer-backend
      dockerfile: ./Dockerfile
    container_name: api-tracer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      BBDD_HOST: db
      BBDD_NAME: tracer
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      APP_PORT: 8080
      LOG_LEVEL: DEBUG
      DLL_AUTO: create
    volumes:
      - ./src/main/resources:/app/resources
    depends_on:
      - db
    links:
      - db

  tracer_react:
    build:
      context: ./tracer-frontend
      dockerfile: ./Dockerfile
    container_name: react-tracer
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - tracer_api
    links:
      - tracer_api